<?php
return array (
	'aTidyConfig' => array(
		'clean' 					  => true, 
		'output-xhtml' 				  => true,
	//	'output-xml' 				  => true,
		'show-body-only' 			  => true,
		'drop-proprietary-attributes' => true, 
		"drop-font-tags"			  => true, 
		"drop-empty-paras" 			  => true, 
		"hide-comments" 			  => true, 
		'word-2000' 			      => true, 
		"join-classes" 				  => true, 
		"join-styles" 				  => true,
		"add-xml-space" 			  => true,
		"enclose-text"				  => true,
		'doctype' 					  => 'strict',
		'logical-emphasis' 			  => true,
		'quote-nbsp' 				  => true,
		'numeric-entities'  		  => true,
		'assume-xml-procins'		  => true,
		'hide-comments'		          => true,
		'quote-ampersand'	          => true,
						),
		);	